version: "3.1"
services:
  loadbalancer:
    image: ngnlinxload
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - redis
      - socket1
      - socket2
    restart: unless-stopped
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379"

  socket1:
    image: socket-server
    build:
      dockerfile: /Dockerfile
    depends_on:
      - redis
    #  ports:
    #    - "8081:8080"

  socket2:
    image: socket-server
    build:
      dockerfile: /Dockerfile
    depends_on:
      - redis
    #  ports:
    #    - "8082:8080"
